//===- ConstraintTypes.h - Constraint Custom Type Declarations ----*- C++ -*-=//
//
// Declares the custom types for the Constraint dialect:
//   !constraint.Sequence      — musical pitch-class sequence
//   !constraint.Dial          — 3D tradition-space position
//   !constraint.VoiceLeading  — voice-leading path
//
//===----------------------------------------------------------------------===//

#ifndef CONSTRAINT_CONSTRAINT_TYPES_H
#define CONSTRAINT_CONSTRAINT_TYPES_H

#include "mlir/IR/Types.h"
#include "mlir/IR/TypeSupport.h"
#include "mlir/IR/MLIRContext.h"

#define GET_TYPEDEF_CLASSES
#include "Constraint/ConstraintTypesGen.h.inc"  // would be generated by TableGen

namespace mlir {
namespace constraint {

//===----------------------------------------------------------------------===//
// SequenceType — !constraint.Sequence
//===----------------------------------------------------------------------===//
//
// Represents a musical sequence of pitch classes. Semantically a variable-
// length array of integers in [0, 11]. Lowered to memref<?xi32>.
//
// Mnemonic: "Sequence"
//
class SequenceType
    : public mlir::Type::TypeBase<SequenceType, mlir::Type,
                                  mlir::TypeStorage> {
public:
  using Base::Base;

  /// Provide a static mnemonic for MLIR's type parsing infrastructure.
  static constexpr llvm::StringLiteral getMnemonic() { return {"Sequence"}; }

  /// Parse from `!constraint.Sequence`.
  static mlir::Type parse(mlir::AsmParser &parser);
  void print(mlir::AsmPrinter &printer) const;
};

//===----------------------------------------------------------------------===//
// DialType — !constraint.Dial
//===----------------------------------------------------------------------===//
//
// Represents a position in 3D tradition space: (harmonic, rhythmic, spectral).
// Each component is in [0.0, 1.0]. Lowered to a struct/tuple of three f64.
//
// Mnemonic: "Dial"
//
class DialType : public mlir::Type::TypeBase<DialType, mlir::Type,
                                              mlir::TypeStorage> {
public:
  using Base::Base;

  static constexpr llvm::StringLiteral getMnemonic() { return {"Dial"}; }

  static mlir::Type parse(mlir::AsmParser &parser);
  void print(mlir::AsmPrinter &printer) const;
};

//===----------------------------------------------------------------------===//
// VoiceLeadingType — !constraint.VoiceLeading
//===----------------------------------------------------------------------===//
//
// Represents a voice-leading path between two sequences. Lowered to
// memref<?xi32> storing the mapping indices.
//
// Mnemonic: "VoiceLeading"
//
class VoiceLeadingType
    : public mlir::Type::TypeBase<VoiceLeadingType, mlir::Type,
                                  mlir::TypeStorage> {
public:
  using Base::Base;

  static constexpr llvm::StringLiteral getMnemonic() { return {"VoiceLeading"}; }

  static mlir::Type parse(mlir::AsmParser &parser);
  void print(mlir::AsmPrinter &printer) const;
};

} // namespace constraint
} // namespace mlir

#endif // CONSTRAINT_CONSTRAINT_TYPES_H
